### ISSUE TITLE
Charts in index.html not Redirecting to Other HTML Pages

### ISSUE THREAD

**Issue by Bharadwaj-0203** [pradeepreddymacha/TechTrack#2]
When clicking on the charts (CPU Usage) in the index.html page of the TechTrack Dashboard, the expected behavior is to redirect to corresponding HTML pages (cpumetrics.html). However, this functionality is not working as intended.

**Comment by pradeepreddymacha** [comment]
Alright I'm working on it now I will push the changes soon.

**Comment by pradeepreddymacha** [comment]
I have resolved the issue on redirection issue on index.html file. Please find changes at commit 4ba2357c6472f6cc3834cbb57cd15dc78aa8b4e5. Pull the latest and let me know if you can see the changes.

**Comment by Bharadwaj-0203** [comment]
Great to hear that the issue has been resolved! the redirection on the index.html file is now working as expected.
