### ISSUE TITLE
Network Metrics Reporting Null Values

### ISSUE THREAD

**Issue by pradeepreddymacha** [pradeepreddymacha/TechTrack#3]
@Bharadwaj-0203 When looking at the network metrics it seems they are receiving null values instead of the usual network stats. Please try to resolve ASAP.

**Comment by Bharadwaj-0203** [comment]
i resolved the issue by removing empty constructor. i just pushed the changes

**Comment by pradeepreddymacha** [comment]
Verified. Thank you.
