### ISSUE TITLE
Static system details collection.

### ISSUE THREAD

**Issue by pradeepreddymacha** [pradeepreddymacha/TechTrack#4]
@PradeepReddy-Baireddy please make sure that static system details are collected only once. I have notice that they are refreshing every 15 seconds.

**Comment by PradeepReddy-Baireddy** [comment]
I resolved this isuue by taking the "collecting metrices" function out of the while loop, So that it would collect only once when we started the application.

**Comment by pradeepreddymacha** [comment]
Great. Thank you
