### ISSUE TITLE
Network metrics collection

### ISSUE THREAD

**Issue by PradeepReddy-Baireddy** [pradeepreddymacha/TechTrack#5]
Network metrics are showing random values, Plesae make sure that they are properly collected and displayed.

**Comment by pradeepreddymacha** [comment]
guys I have updated networkmertics.html and networkmertics accordingly please verify.

**Comment by Bharadwaj-0203** [comment]
added AggregatedNetworkMetrics class and updated NetworkMetricsController class. please verify it.

**Comment by PradeepReddy-Baireddy** [comment]
I verified it. its working
