### ISSUE TITLE
Test Cases Running Twice in Maven Build due to Test Suites Execution

### ISSUE THREAD

**Issue by Bharadwaj-0203** [pradeepreddymacha/TechTrack#6]
During Maven build, the test cases in our project are running twice. This occurs first when they execute normally, and then again during test suites execution. please resolve this.

**Comment by PradeepReddy-Baireddy** [comment]
Resolved it by removing TestSuite class, so that repeating won't occur.

**Comment by Bharadwaj-0203** [comment]
Thank you for addressing. The issue got resolved.
